### PR TITLE
Feature/windows wifi switching

### PR DESCRIPTION
**Pull request by m-mcgowan**
Automatic wifi switching on Windows as part of the setup process.

### CODE REVIEW

**Comment by monkbroc** [comment]
One thing I saw is that the check if the Photon is online is way too aggressive. Wi-Fi switching on Windows took less than 1 second and it immediately said It doesn't look like your Photon has mad it to the cloud yet. Can we change this code to add 10 retries with a delay of 1 second in between each before we show the message?

**Comment by monkbroc** [comment]
I also tested on a computer without Wi-Fi. I got this error:
```
> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
! The device supports setup via serial.
Serial err: Error: Opening COM6: Access denied
Serial problems, please reconnect the device.
Serial problems, please reconnect the device.
Potentially unhandled rejection [3] Serial problems, please reconnect the device. (WARNING: non-Error used)
```

**Comment by monkbroc** [comment]
Trying again on a Windows computer without a Wi-Fi card gave this (not sure why it's different):
```
> Setup is easy! Let's get started...
> It appears as though you are already logged in as julien@particle.io
? Would you like to use this account? Yes

! PROTIP: Hold the MODE/SETUP button on your device until it blinks blue!
! PROTIP: Please make sure you are connected to the internet.

> I have detected a Photon connected via USB.
? Would you like to continue with this one? Yes
▄ Getting device information...Serial err: Error: Opening COM6: Access denied
Serial problems, please reconnect the device.
! The Photon supports secure Wi-Fi setup. We'll try that.

! PROTIP: Wireless setup of Photons works like a wizard!
! PROTIP: We will automagically change the Wi-Fi network to which your computer is connected.
! PROTIP: You will lose your connection to the internet periodically.

> No nearby Photons detected. Try the `particle.js help` command for more information.
? Would you like to wait and monitor for Photons entering setup mode? No

> Ok, bye! Don't forget `particle.js help` if you're stuck! <3
```

Note that the first time I tried to do Wi-Fi setup I also got the `Opening COM6: Access denied` error, I just didn't notice since Wi-Fi setup worked on the computer with Wi-Fi.

**Comment by m-mcgowan** [comment]
Would you mind trying serial again and no-wifi? I rebased on the Serial setup PR that's now merged and setup seems smoother. I tested setup over Serial on Windows and it worked fine.  I don't have a networked machine without wifi, but I did unplug my wifi dingle at the appropriate point and it got as far as trying to verify the device came online, so I would hope that is also working.

**Comment by m-mcgowan** [comment]
Fixes https://github.com/spark/particle-cli/issues/258

**Pull request merged**
