### PR TITLE
Grammatical Fix

### PR DESCRIPTION
**Pull request by littulb**
Grammatical Fix

### CODE REVIEW

**Comment by kennethlimcp** [comment]
@littulb thanks!

**Comment by littulb** [comment]
Hello Kenneth,

No problem. I made the fix in order to join the slack channel. Can you please pass the info to the person who governs the slack channel invites? Thanks a lot. Looking forward to building great things with you guys.

**Comment by brycekahle** [comment]
@littulb Would you mind signing our [CLA](https://docs.google.com/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform)? Go ahead and ping me afterwards, and I will get this merged.

**Comment by brycekahle** [comment]
Closing due to inactivity. If you wish to re-open this pull request, please sign the CLA and comment here.

**Pull request closed without merging**
