### PR TITLE
voodoospark v3.0.0

### PR DESCRIPTION
**Pull request by rwaldron**
CLA Signed.

### CODE REVIEW

**Comment by emilyrose** [comment]
Oh hey, thanks! :heart:

**Comment by rwaldron** [comment]
That's some serious hustle—thanks!!!

**Comment by emilyrose** [comment]
no no, thank *you*! :wink: 

https://github.com/spark/particle-cli/releases/tag/v1.8.6
https://www.npmjs.com/package/particle-cli
https://github.com/spark/particle-cli/blob/master/CHANGELOG.md#changelog

**Comment by rwaldron** [comment]
Woo!

Here is the run down for vs-3.0.0: https://github.com/voodootikigod/voodoospark/releases/tag/3.0.0

**Pull request merged**
