### PR TITLE
Implements the --follow option in the "serial monitor" command.

### PR DESCRIPTION
**Pull request by derekmpeterson**
Addresses #234 - Invoking the command with --follow will poll for an available serial device, and when one becomes available, immediately connect.  If the connection is interrupted, it will attempt to reconnect when the device is available again.

The monitor will reconnect automatically after rebooting or reflashing the device.  This makes debugging much more convenient.

While I was in there, in response to a TODO comment, I also added an interrupt handler to attempt to gracefully clean up the serial connection on SIGINT, SIGQUIT, SIGTERM, or exit.

### CODE REVIEW

**Comment by monkbroc** [comment]
Thanks for the contribution. l need a little time to take a look at the code.

**Comment by m-mcgowan** [comment]
Nice work @derekmpeterson, thanks!

Tested with and without the `--folllow` flag with 0, 1 and 2 devices connected to serial.

**Comment by m-mcgowan** [comment]
This PR will automatically close once the changes are moved to master. Should have edited the base and changed from master to develop.

**Comment by KravitzLab** [comment]
I have tried "particle serial monitor --follow" and after my photon goes to sleep and wakes up again, the command line doesn't monitor the serial COM anymore! This is the same problem with PuTTY as well...

**Comment by kennethlimcp** [comment]
@KravitzLab something like CoolTerm should suit your needs. 

Which OS are you on? I will need to try this `--follow` flag on my side as well.

**Comment by KravitzLab** [comment]
@kennethlimcp I got this solution off: https://community.particle.io/t/putty-or-other-serial-monitor-that-automatically-reconnects-windows/33579/7 check the comment made by rickkas7. I'll check CoolTerm out, but in case anyone else is reading this thread: Tera Term seems to be working as well. 

I am running Windows 7. Check it out and let me know what you get! I think this functionality is quite important to users developing low power systems, and debug Particle products after sleep.

**Pull request merged**
