### PR TITLE
Added the ability to specify a .json file to skip the wifi prompts

### PR DESCRIPTION
**Pull request by markterrill**
Hi,
Taken the liberty of adding the ability to specify a .json file with the wifi settings you want to push. This skips the need to either write an expect script or do it manually for x hundred particle devices.

As the serial command currently expects any 'extra' arguments to be the serial com device, you need to append the .json argument to the end, ie: 
particle serial wifi /dev/cu.usbmodem1411 variables.json

variables.json looking like:
{
    "network":"mynetworkssid",
    "security":"WPA_AES",
    "password":"mySecret!"
}

### CODE REVIEW

**Comment by markterrill** [comment]
PS, used an external file in preference to more arguments as then the file can be secured outside of direct application code in a startup/setup script

**Comment by brycekahle** [comment]
@markterrill Would you mind signing the CLA as described [here](https://github.com/spark/particle-cli/blob/master/CONTRIBUTING.md)? Thanks.

**Comment by markterrill** [comment]
Done!


--
Mark Terrill | 0412 704 411

On 22 Apr 2016, at 03:03, Bryce Kahle <notifications@github.com<mailto:notifications@github.com>> wrote:


@markterrill<https://github.com/markterrill> Would you mind signing the CLA as described here<https://github.com/spark/particle-cli/blob/master/CONTRIBUTING.md>? Thanks.

**Comment by markterrill** [comment]
Done

**Comment by technobly** [comment]
This is great! You can put something like this into your `.bash_profile` to target specific port of a USB hub with labeled cables, e.g. #1 - #6.  Here’s the function for cable #2. Done this way so credentials are not stored in a random file and place on my computer.

```c
alias listen2='stty -f /dev/cu.usbmodem141431 28800'

function wifi2()
{
  echo '{"network":"MY_SSID","security":"WPA2_AES","password":"MY_SUPERPASSWORD"}' > whatchamacallit.json
  particle serial wifi /dev/cu.usbmodem141431 whatchamacallit.json
  rm whatchamacallit.json
}
```

With these two aliases you can automatically put your device in Listening Mode and update it's WiFi Credentials.  Feel free to create aliases for other labeled ports :)

```c
$ listen2 && wifi2
```

**Comment by markterrill** [comment]
That's neat, glad you like it!

I have a node script that uses async.series to step through dfu, new firmware, changing wifi suffix, configuring wifi, claiming and flashing app firmware. The json file was to make it easy to a) to do wifi cress without human error and effort, manual input is crazy b) use a file so it was clear where multiple credential sets were stored and easy to switch between my test network credentials and my manufacturers based on detecting the local network.

Mark

Sent from my iPhone

On 9 Feb 2017, at 6:20 am, Brett Walach <notifications@github.com<mailto:notifications@github.com>> wrote:


This is great! You can put something like this into your .bash_profile to target specific port of a USB hub with labeled cables, e.g. #1<https://github.com/spark/particle-cli/issues/1> - #6<https://github.com/spark/particle-cli/issues/6>. Here’s the function for cable #2<https://github.com/spark/particle-cli/issues/2>. Done this way so credentials are not stored in a random file and place on my computer.

alias listen2='stty -f /dev/cu.usbmodem141431 28800'

function wifi2()
{
  echo '{"network":"MY_SSID","security":"WPA2_AES","password":"MY_SUPERPASSWORD"}' > whatchamacallit.json
  particle serial wifi /dev/cu.usbmodem141431 whatchamacallit.json
  rm whatchamacallit.json
}

With these two aliases you can automatically put your device in Listening Mode and update it's WiFi Credentials. Feel free to create aliases for other labeled ports :)

$ listen2 && wifi2

**Pull request closed without merging**
