### PR TITLE
Test for photon vendorid in findcores for win10 no driver -- fix #10

### LINKED ISSUE #10: particle setup doesnt work without a driver on Windows 10
Windows 10 has a usb serial driver so you didn't need to install the Windows Driver. I made a change that made this work with the spark core by checking the vendor id right in the pnpid string. This doesn't work with the photon since there's a new vendor and product id for the photon.

### PR DESCRIPTION
**Pull request by dwcares**
Fix for  #10

Here is an idea for testing for different device types while allowing for the no-driver scenario on windows 10 which doesn't have all of the device properties.

perhaps this could be better serviced by a getDeviceType helper? w00t and happy birthday dave! :) :+1:

### CODE REVIEW

**Comment by dmiddlecamp** [comment]
:). Thanks Dave!

**Comment by emilyrose** [comment]
hey @dwcares, thanks for this! the code base has diverged significantly since you submitted this (my fault for not checking this out sooner). I'd love to incorporate this, but I also want to give you the chance to update the pull request first.

let me know what you think!

**Comment by kennethlimcp** [comment]
This has been fixed already with the serial detection improvement PR no?

**Comment by brycekahle** [comment]
Fixed via https://github.com/spark/particle-cli/commit/4f483a1a495ea9f9f091ea0be51334b8a3bbe4f7

**Pull request closed without merging**
